### ISSUE TITLE
资源消耗疑问

### ISSUE THREAD

**Issue by kesonn** [LangziFun/LangSrcCurise#15]
资源消耗已经增加id到200+了，之前的id在列表里一直存在。这个资源消耗不会自动释放的吗，会一直累加？

可否手动删除，疑问，求解答～～

多谢大佬！

**Comment by LangziFun** [comment]
资源消耗只是记录每两个小时之内的CPU,内存，宽带使用量。仅仅记录而已~无需释放，删除操作
