### ISSUE TITLE
请问更新要怎么更新，把代码直接覆盖可以不

### ISSUE THREAD

**Issue by kesonn** [LangziFun/LangSrcCurise#18]
请问更新要怎么更新，把代码直接覆盖可以不

**Comment by Pa55w0rd** [comment]
我没有覆盖，数据库和我之前那版数据库结构变了，重新安装一遍吧

**Comment by LangziFun** [comment]
覆盖代码后，执行命令1 python3 manage.py makemigrations 2 python3 manage.py migrate，然后登陆后台-->监控域名-->设置是否监控为是
