### ISSUE TITLE
secret是硬编码

### ISSUE THREAD

**Issue by k3mlol** [LangziFun/LangSrcCurise#3]
https://github.com/LangziFun/LangSrcCurise/blob/7ccb1613b1c73161ef06abaab0574a97740857f4/LangSrcCurise/settings.py#L39

建议修改，可参考巡风
https://github.com/ysrc/xunfeng/blob/c9fad9d5af1379473155d0770f3f66fc4e53f3d4/views/__init__.py#L10

**Comment by LangziFun** [comment]
收到，感谢您的建议

**Comment by k3mlol** [comment]
> 收到，感谢您的建议
