### ISSUE TITLE
数据展示表的很多地方是None，网络资产表却没问题

### ISSUE THREAD

**Issue by W3lk1n** [LangziFun/LangSrcCurise#32]
数据展示表的很多地方是None，网络资产表却没问题？

**Comment by LangziFun** [comment]
因为您没有开启扫描开放端口任务和清洗数据任务。
具体开启方法请仔细阅读帮助文档后，取消注释两行代码即可。

**Comment by W3lk1n** [comment]
谢谢，不过readme没看到任何清洗数据的描述，希望后面加上。

**Comment by LangziFun** [comment]
收到，感谢反馈
