### ISSUE TITLE
运行了一晚上捕获0

### ISSUE THREAD

**Issue by 211guns** [LangziFun/LangSrcCurise#6]
系统centos7，相关都已安装，貌似不启动捕获啊
运行python3 manage.py startscan  提示 killd正常吗？

**Comment by LangziFun** [comment]
自动屏蔽了GOCEDU相关域名，如有需求自行修改

**Comment by 211guns** [comment]
没有edu之类的域名啊，就是cn com， 另外修改位置在哪里？
